### ISSUE TITLE
Create gallery?

### ISSUE THREAD

**Issue by AnnaMariaEriksson** [MichaelArestad/Press-This#104]
I've played around a little with this awesome thing, but I can't seem to create a gallery. The only option from what I understand is to upload files (as usual), but what if I'd like the embedded photos in the post (fetched from a website) to be the gallery? If I add the post format "gallery" nothing special happens.

Please add this feature. Thanks!

**Comment by kraftbj** [comment]
From the version currently in WordPress trunk, you can click the arrow next to "Insert Media" to insert other things besides single images:

https://cloudup.com/cW0cOeQppgO

**Comment by kraftbj** [comment]
Missed the `(fetched from a website)` piece.

**Comment by stephdau** [comment]
Hi there. The images being presented to you from the source page have not yet been downloaded to your WP instance, so they're not yet available for you to make a gallery yet. This is unlikely to change, because WP requires for the images to be local to create galleries (it uses the attachment ID, for example).

On the other hand, there is one way to do it, albeit with some work.
1. "Press" a page, see detected images.
2. Insert the ones you'd like to create a gallery from in the Press This editor by clicking each one.
3. Save as draft, which will send you to the full editor
4. Now those images have been copied to your WP install, and you can now make a gallery from them.

**Comment by AnnaMariaEriksson** [comment]
Thank you for that tip! It did work, but the gallery does not look that great. Also the best part is that they were still linked to the pressed page, and that's really good, since I don't wanna take up any space on my blog, really. Thanks again!
