### ISSUE TITLE
Still planning to use WP API for initial release?

### ISSUE THREAD

**Issue by MichaelArestad** [MichaelArestad/Press-This#18]

**Comment by stephdau** [comment]
It won't be ready for us to, unfortunately.

On the other hand, switching to it once it is should be trivial, since the only interaction with the backend is limited to saving the post: https://github.com/MichaelArestad/Press-This/blob/master/js/app.js#L242

This might change as we start using the media library though.

**Comment by MichaelArestad** [comment]
Cool. Adding a future release label.
