### ISSUE TITLE
Integrate new image flow media modal

### ISSUE THREAD

**Issue by MichaelArestad** [MichaelArestad/Press-This#20]

**Comment by stephdau** [comment]
That also won't be ready for our initial release targeted for 4.2 (like the JSON API), since their timeline for inclusion is currently looking like 4.4. The good news is that 4.0/4.1 have seen some mobile related UX/UI improvements that now make the existing modal viable. And one imageflow makes it into core, we'll gain all of it, since it'll replace the current media library.

**Comment by MichaelArestad** [comment]
Sounds like a plan.

**Comment by stephdau** [comment]
All done.

**Comment by stephdau** [comment]
Done, as in, we've implemented the media library, which means that we'll get imageflow once it makes it into core (or will do the work then, like everybody else).
